### ISSUE TITLE
SQS Queues Without Server-Side Encryption

### ISSUE THREAD

**Issue by kra5io** [widdix/aws-s3-virusscan#100]
Hello Team,

I see no option for sqs encryption. When I think about it, I don't really see a reason to enable SQS encryption, but we have a request from the customer asking to enable it. Except creating additional cost, this seems useless, as the whole solution is dropping the infected files or letting them through if not right?

Thanks in advance for your answer,
Krasi

**Comment by michaelwittig** [comment]
Hi @kra5io 
The messages sent to SQS contain object meta data like bucket name, object key. I don't consider this sensitive information.
But feel free to enable SSE on the SQS queues by modifying the template. PR is welcome.

**Comment by kra5io** [comment]
Hi @michaelwittig 
I am just worried encryption will add additional cost and bring no real value. Wanted to confirm with you
Cheers
