### ISSUE TITLE
a few concerns.

### ISSUE THREAD

**Issue by SPrakash101** [widdix/aws-s3-virusscan#13]
Thank you so much for this. It is useful but we had some security concerns.

The cloud formation installs the s3-virusscan server (CLAMAV workers) with a security group which has SSH port open to 0.0.0.0/0 ? Is this necessary? Can we remove this?

Also, can we put on rules to block the CLAMAV workers from communicating from the outside world - 127.0.0.1/32 

What are the security considerations to take and what are the risks?

**Comment by michaelwittig** [comment]
if you don't like to have SSH access, just remove the security group rule. the solution will still work.

the clam av workers need access to the Internet for

a) updating the virus database
b) interacting with the aws api: downloading files from s3 and communicating with sqs

you could put natting or a proxy in between if you like.
