### ISSUE TITLE
No export named -SubnetBPublic found. Rollback requested by user.

### ISSUE THREAD

**Issue by mf-bmihaescu** [widdix/aws-s3-virusscan#15]
Hi

Should I create my own VPC or it's created automatically ?
Should i also manually add the subnets ?

Thanks

**Comment by michaelwittig** [comment]
why not just following the installation instructions? https://github.com/widdix/aws-s3-virusscan#installation

**Comment by deependersingla** [comment]
@michaelwittig  I also got same error while creating second [stack](https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates/vpc/vpc-endpoint-s3.yaml), first one created fine. Anything I am doing wrong. 

Thanks

**Comment by michaelwittig** [comment]
You must use one of our VPC templates: https://github.com/widdix/aws-cf-templates/tree/master/vpc
They all export `SubnetBPublic`

**Comment by deependersingla** [comment]
Thanks a lot for the reply, I used https://s3-eu-west-1.amazonaws.com/widdix-aws-cf-templates/vpc/vpc-2azs.yaml and it was created successfully also.  (screenshot attached in the end). The second stack s3-virusscan give the error: 
> No export named -SubnetAPublic found. Rollback requested by user.(screenshot also in the end)

![image](https://cloud.githubusercontent.com/assets/3043621/24994579/1b225462-2049-11e7-821f-b1fc023d6566.png)

![image](https://cloud.githubusercontent.com/assets/3043621/24994681/8d0b0aec-2049-11e7-8031-570f3dbd91a7.png)

**Comment by michaelwittig** [comment]
You need to enter `vpc-2azs` during creation of the second stack in the `ParentVPCStack` parameter.

**Comment by deependersingla** [comment]
thanks, this solved the error. But, I get this error: 
`` Unable to satisfy 100% MinSuccessfulInstancesPercent requirement. 

I will submit a pull request with updated Readme when installation is done.

![image](https://cloud.githubusercontent.com/assets/3043621/24996294/f053afb8-204f-11e7-80f1-e82979b55519.png)
