### ISSUE TITLE
Use other antivirus solutions

### ISSUE THREAD

**Issue by anujgeek** [widdix/aws-s3-virusscan#18]
Can we make this solution work with other paid antivirus solutions? If yes, can you please recommend some and explain the process. Thanks in advance!

**Comment by michaelwittig** [comment]
Hi @anujgeek
If the paid antivirus solution provides a way to scan a file using the cli, yes.

The line you have to modify: https://github.com/widdix/aws-s3-virusscan/blob/master/template.yaml#L581

`clamdscan #{fileName}` is the way to scan a file with ClamAV.
Replace `clamdscan` with whatever is provided by your antivirus solution. Contract is that is returns a success exit coe if the file is clean, otherwise a non zero exit code.

**Comment by anujgeek** [comment]
Hi @michaelwittig, thanks for replying back.
I'm looking at Bitdefender business products and they do provide a cli interface along with UI.
I'll also have to tweak the yaml file to not install ClamAV and install Bitdefender in AWS EC2 instance. I'm also hoping that the Bitdefender auto-update service should take care of updates and I won't have to worry about updating from cli.
Can you please let me know how to tweak the yaml file to not install ClamAV. Also, how can I login to that EC2 instance to install Bitdefender there. I'm on my AWS EC2 console and can't figure out how to connect to that instance:
![image](https://user-images.githubusercontent.com/16366917/28294041-68c35bd6-6b0c-11e7-9911-83bd7ea3f5bc.png)

**Comment by michaelwittig** [comment]
Hi @anujgeek You used CloudFormation to create stack? During the process you provide some parameters, one of them is called `KeyName`. This is where you should enter the name of the EC2 key pair that you can then use to connect via SSH. You can update the existing stack to change the parameter!

Regarding the other question of installing Bitdefender: How is the software packaged? maybe an rpm file that you can use?

**Comment by anujgeek** [comment]
Yes, I did use the CloudFormation to create stack. I deleted and recreated the stack after creating and associating a key pair, but I was only able to login using key 'ec2user' as username, but not the key name I provided. I used the same pem/ppk file though.
Bitdefender licensing and deployment models were complex, so I switched to using Avast. They do provide rpm packages (http://files.avast.com/lin/repo/dists/rhel/release/x86_64/) and installation instructions (http://deb.avast.com/lin/doc/techdoc.pdf Page 3). I'm new to linux, so I wasn't able to figure out how to execute these:
1. Add the Avast repository to the system repositories:
# echo '[avast]
name=Avast
baseurl=http://rpm.avast.com/lin/repo/dists/rhel/release
enabled=1
gpgcheck=1' > /etc/yum.repos.d/avast.repo
# rpm --import /path/to/avast.gpg
2. Install the avast package
packages.
# yum install avast
Can you please help me in using the avast package in yaml file or using ssh terminal?

**Comment by michaelwittig** [comment]
@anujgeek the username is always ec2-user (on Amazon Linux) and is not related to your key name.

you can add the three commands here: https://github.com/widdix/aws-s3-virusscan/blob/master/template.yaml#L688

you can find the docs here: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html
