### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by syed0000** [widdix/aws-s3-virusscan#20]
During creation of cloud formation stack... Its not displaying detail about ec2 instance on dashboard as well its not working properly...
Without vpc concept I wnt to start it for s3 scaning

**Comment by michaelwittig** [comment]
what is the status of the cloudformation stack you created?

**Comment by syed0000** [comment]
Not fine Sir..
I m not able to see where is the instance which is launch what should I
have to do with it...means stucked
If you can help me than pls do
