### ISSUE TITLE
ROLLBACK_IN_PROGRESS

### ISSUE THREAD

**Issue by funktrust** [widdix/aws-s3-virusscan#21]
ROLLBACK_IN_PROGRESS

I am getting a ROLLBACK_IN_PROGRESS when trying to install the template.yml from https://github.com/widdix/aws-s3-virusscan into my existing infrastructure.

Using:

- vpc-2azs.yaml
- vpc-ssh-bastion.yml
- vpc-nat-gateway.yml
- vpc-endpoints-s3.yml

Seems to be an issue with autoscaling. But I am unable to troubleshoot this. I was wondering if you know what could be the issue?

**Comment by michaelwittig** [comment]
Hi @funktrust 

Please delete the failed stack and create a new stack where you disable **Rollback on failure** in the Advanced **Options** step of the wizard. Then you can check the logs reported to CloudWatch logs for the root cause,

**Comment by funktrust** [comment]
Thanks for the fast reply.

I had a look in the logs like you suggested and see its failing during clamav update.

var/log/messages
`
22:44:07
Aug 28 12:44:07 ip-10-10-42-252 yum[3086]: Installed: clamav-update-0.99.2-1.27.amzn1.x86_64

22:44:18
Aug 28 12:44:18 ip-10-10-42-252 dhclient[2231]: XMT: Solicit on eth0, interval 68460ms.

22:44:27
Aug 28 12:44:27 ip-10-10-42-252 freshclam[3182]: ClamAV update process started at Mon Aug 28 12:44:27 2017

22:44:32
Aug 28 12:44:32 ip-10-10-42-252 freshclam[3182]: getfile: main-58.cdiff not found on database.clamav.net (IP: 193.1.193.64)

22:44:32
Aug 28 12:44:32 ip-10-10-42-252 freshclam[3182]: getpatch: Can't download main-58.cdiff from database.clamav.net

22:44:32
Aug 28 12:44:32 ip-10-10-42-252 freshclam[3182]: getpatch: Can't download main-58.cdiff from database.clamav.net

22:44:32
Aug 28 12:44:32 ip-10-10-42-252 freshclam[3182]: getpatch: Can't download main-58.cdiff from database.clamav.net

22:44:32
Aug 28 12:44:32 ip-10-10-42-252 freshclam[3182]: Incremental update failed, trying to download main.cvd

22:44:34
Aug 28 12:44:34 ip-10-10-42-252 freshclam[3182]: getfile: main.cvd not found on database.clamav.net (IP: 193.1.193.64)

22:44:34
Aug 28 12:44:34 ip-10-10-42-252 freshclam[3182]: Can't download main.cvd from database.clamav.net`

**Comment by michaelwittig** [comment]
maybe there is an issue with database.clamav.net ?

**Comment by johndavi** [comment]
This still seems to be an issue -- I'm following instructions exactly and creation fails every time at ScanAutoScalingGroup. Any thoughts/updates/debugging tips? Thank you.

**Comment by johndavi** [comment]
My mistake: the issue was one of spot price. I had to increase the spot price from the default for my region.
