### ISSUE TITLE
No Exports Found For 

### ISSUE THREAD

**Issue by hyattdrew11** [widdix/aws-s3-virusscan#22]
Cloud formation build from this template fails. 
No export named "ParentVPC" found or No export named "###"-SubnetBPublic found

**Comment by michaelwittig** [comment]
1. Have you created a CloudFormation stack for the VPC based on those templates https://github.com/widdix/aws-cf-templates/tree/master/vpc ?
2. Have you passed in the name of the vpc stack as the `ParentVPC` parameter in the virusscan stack?
