### ISSUE TITLE
Unsure what to do with some aws-s3-virusscan alerts

### ISSUE THREAD

**Issue by kevinm** [widdix/aws-s3-virusscan#23]
We're using the aws-s3-virusscan tool and have found it to be very helpful. Thank you for putting it together, your work is much appreciated.

We received this alert today and don't know if it's something we should be doing something about or if it can be safely ignored. Where is the right place to look to get a list of alarms and what to do with them. Some of the alarms are well documented enough in the alarm to determine how to proceed. 'Add one instance', 'Remove one instance', etc. But ones like this 'Alarm if dead letter queue has messages' are harder to know what to do with.

If this is something I can help with let me know. I don't just want to bring problems to you without offering any assistance or help.

Thanks
  Kevin

You are receiving this email because your Amazon CloudWatch Alarm "s3-virusscan-ScanQueueDLQAlarm-redacted" in the redacted region has entered the ALARM state, because "Threshold Crossed: 1 datapoint [42.0 (04/12/17 02:50:00)] was greater than or equal to the threshold (1.0)." at "Monday 04 December, 2017 02:51:16 UTC".

View this alarm in the AWS Management Console:
https://console.aws.amazon.com/cloudwatch/home?region=redacted

Alarm Details:
- Name:                       s3-virusscan-ScanQueueDLQAlarm-redacted
- Description:                Alarm if dead letter queue has messages
- State Change:               INSUFFICIENT_DATA -> ALARM
- Reason for State Change:    Threshold Crossed: 1 datapoint [42.0 (04/12/17 02:50:00)] was greater than or equal to the threshold (1.0).
- Timestamp:                  Monday 04 December, 2017 02:51:16 UTC
- AWS Account:                redacted

Threshold:
- The alarm is in the ALARM state when the metric is GreaterThanOrEqualToThreshold 1.0 for 60 seconds.

Monitored Metric:
- MetricNamespace:                     AWS/SQS
- MetricName:                          ApproximateNumberOfMessagesVisible
- Dimensions:                          [QueueName = s3-virusscan-ScanQueueDLQ-redacted]
- Period:                              60 seconds
- Statistic:                           Sum
- Unit:                                not specified

State Change Actions:
- OK:
- ALARM: [arn:aws:sns:redacted:redacted:s3-virusscan-FindingsTopic-redacted]
- INSUFFICIENT_DATA:

**Comment by michaelwittig** [comment]
@kevinm Could you check CloudWatch Logs for errors? Looks like a file could not be scanned.

**Comment by kevinm** [comment]
My apologies. I got pulled into an end of year push on other projects that I'm just finished up with and have time to dig into this again. We're still having the dead letter queue problem and at this point we have 227 items in the queue. I looked at the CloudWatch logs and I'm not seeing anything that indicates that the messages can't be processed but I don't know which log I should be looking in or what a typical message indicating a failure to process a log would be.

So a few questions/requests.
* What is the best way to see the messages in the dead letter queue?
* Can we be notified of the specific S3 object that is stuck in the dead letter queue? Right now if an file is received but is not able to be processed I expect we have to dig through the DLQ to find it and remove it. It would be nice if this was automated but this is probably something that the end users can do. Even better would be if there was an option to delete both the problematic S3 object and the item in the queue.
* What is the best way to clear out the messages in the dead letter queue?

Different question entirely. Right now we're not automatically deleting infected files. Is there a way to enable that without rebuilding the whole CloudFormation stack? It's not too much trouble to rebuild the CloudFormation stack but it sure would be nice to be able to flip that bit rather than tearing it all down.

Thanks again for any assistance on this and my long delay getting back to you on this. I'm doing a lot of heads down work over the next few weeks so I'll be able to get back to you quickly if you need any information from me.

Best,
   Kevin

**Comment by michaelwittig** [comment]
you can go to the SQS Service in the management console to look at the messages and purge all messages.
