### ISSUE TITLE
Why are versioned buckets not supported?

### ISSUE THREAD

**Issue by jgrumboe** [widdix/aws-s3-virusscan#28]
Hi,
thanks for this template, i appreciate it!
i would like to know what's the point behind "versioned buckets are not supported"?
Best regards,
Johannes

**Comment by michaelwittig** [comment]
HI @jgrumboe 
it's not implemented.

**Comment by jgrumboe** [comment]
Hi @michaelwittig ,
ok, one last question: so do you mean versioned buckets cannot be used in any way or your code currently only scans the latest version and not deeper (older versions)?
Thanks for your help,
Johannes

**Comment by michaelwittig** [comment]
the latest version will be scanned. If you upoload multiple versions of the same file, chances are high that some versions are not scanned.

**Comment by jgrumboe** [comment]
Thx, so it suits my usecase, since timegap between version is very high in my usecase :)
