### ISSUE TITLE
S3 virusscan and AWS SDK

### ISSUE THREAD

**Issue by gapin** [widdix/aws-s3-virusscan#30]
hi,
do you know if it is possible to enable the s3 virusscan and getting an error response from the:
client.PutObject(request);
when trying to upload content from the dotnet awsdk to the s3 bucket (if virus check is positive) ?

thanks!

**Comment by michaelwittig** [comment]
? this project does not use the .net sdk ?

**Comment by gapin** [comment]
Yes, I lknow. But if the S3 virusscan is enabled, when uploading a file (virus positive) to the bucket from the AWS SDK it results in a OK response, but after a while the file is deleted from the bucket by the virusscan... so I have some consistency problems. I would like to know if there is a way to make a realtime antivirus check in order to get the right response from the AWS SDK. Is it clear?

**Comment by michaelwittig** [comment]
Now I understand. No, that's not possible. The idea is that the virus scan happens asynchronously in the background here.
