### ISSUE TITLE
Scan finished notification

### ISSUE THREAD

**Issue by yurii-ploskyi-kindgeek** [widdix/aws-s3-virusscan#33]
Recently I started use virus scan and found it is very convenient and good tool.

I get notification each time some virus is deleted. However it would be very useful to get also notification when new object are already scanned and no viruses found.

In other words, I want to know when object that was uploaded already scanned and no viruses found.
I understand that such functionality isn't implemented out of the box.
Could you please, advice me how can I implement it ?

Thanks in advance,
Yurii

**Comment by andreaswittig** [comment]
Are you looking for a way to receive a notification after an object was scanned without any findings? If so, you can set the `ReportCleanFiles` to `true` when creating or updating the CloudFormation stack.

**Comment by yurii-ploskyi-kindgeek** [comment]
Thank you for help! It is what i looked for!
And one more problem. When I subscribe to SNS with my email I get notification emails on all events (What is good). However when I subscribe with http endpoint I do not get events about s3 scans to my endpoint. Endpoint is public, I got confirmation event from SNS, however don't get events from s3 virus scan.
Could you please help me with that ? 
Thanks in advance,
Yurii
