### ISSUE TITLE
Identifying bucket from where infected file originated

### ISSUE THREAD

**Issue by tnynyn** [widdix/aws-s3-virusscan#36]
Hi,

Is there a way to tell which bucket the infected file came from? I checked logs but didn't see any info on which bucket it came from.

**Comment by michaelwittig** [comment]
Hi @tnynyn 
which OS are you sing?
can you post the log files that you are checking?

**Comment by tnynyn** [comment]
My apologies, I didnt see the email alert from the virusscan, it contained the bucket name.  I was thinking I'd had to look through logs in CloudWatch.  Thanks for the help though and the virusscanner :)
