### ISSUE TITLE
ClamAV update not working

### ISSUE THREAD

**Issue by krantid2013** [widdix/aws-s3-virusscan#37]
Hi,

I am keep getting following warning in the log and also latest malware is not detected by scan while same file is flagged as infected on the other machine where I have ClamAV 0.100.1. Please help.

ClamAV update process started at Thu Aug  2 01:02:41 2018
Your ClamAV installation is OUTDATED!
Local version: 0.99.4 Recommended version: 0.100.1

**Comment by michaelwittig** [comment]
Amazon Linux comes with clamav 0.99.4 and this can not be changed easily. **But the virus definition is up-to-date.**

The log you show mentions that there is a never clamav version. But this information is not related to the Amazon Linux repository.
