### ISSUE TITLE
Installation question 

### ISSUE THREAD

**Issue by snifsnsort** [widdix/aws-s3-virusscan#39]
Hello,
I'm trying to replicate the installation steps, but in my case the SQS name is not populated and whatever i try to type to create a new one i get invalid ARN message. 
I feel like i'm missing a step . 
Would appreciate any assistance how to get this step done.

**Comment by snifsnsort** [comment]
The second one fails and rolls back. 
Here is the events log from both : 
	23:41:13 UTC-0400	ROLLBACK_COMPLETE	AWS::CloudFormation::Stack	s3-virusscan	
Physical ID:arn:aws:cloudformation:us-east-1:513623109826:stack/s3-virusscan/5ef0fbc0-a686-11e8-b47f-50d5cd26c2d2
Client Request Token:Console-CreateStack-55c7799e-f9d1-459e-87ea-dc393659e719

23:41:11 UTC-0400	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	s3-virusscan	No export named -SubnetAPublic found. Rollback requested by user.
Physical ID:arn:aws:cloudformation:us-east-1:513623109826:stack/s3-virusscan/5ef0fbc0-a686-11e8-b47f-50d5cd26c2d2
Client Request Token:Console-CreateStack-55c7799e-f9d1-459e-87ea-dc393659e719

23:41:08 UTC-0400	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	s3-virusscan	User Initiated
Physical ID:arn:aws:cloudformation:us-east-1:513623109826:stack/s3-virusscan/5ef0fbc0-a686-11e8-b47f-50d5cd26c2d2
Client Request Token:Console-CreateStack-55c7799e-f9d1-459e-87ea-dc393659e719

	23:37:42 UTC-0400	CREATE_COMPLETE	AWS::CloudFormation::Stack	vpc-2azs	
23:37:37 UTC-0400	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPrivate	
23:37:37 UTC-0400	CREATE_COMPLETE	AWS::EC2::Route	RouteTablePublicInternetRoute	
23:37:36 UTC-0400	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPublic	
23:37:36 UTC-0400	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPublic	
23:37:36 UTC-0400	CREATE_COMPLETE	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPrivate	
23:37:35 UTC-0400	CREATE_COMPLETE	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPrivate	
23:37:35 UTC-0400	CREATE_COMPLETE	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPublic	
23:37:35 UTC-0400	CREATE_COMPLETE	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPublic	
23:37:35 UTC-0400	CREATE_COMPLETE	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPrivate	
23:37:35 UTC-0400	CREATE_COMPLETE	AWS::EC2::Route	RouteTablePublicBInternetRoute	
23:37:21 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPrivate	Resource creation Initiated
23:37:21 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Route	RouteTablePublicInternetRoute	Resource creation Initiated
23:37:21 UTC-0400	CREATE_COMPLETE	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPublicAllowAll	
23:37:21 UTC-0400	CREATE_COMPLETE	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPrivateAllowVPC	
23:37:20 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Route	RouteTablePublicInternetRoute	
23:37:20 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPublic	Resource creation Initiated
23:37:20 UTC-0400	CREATE_COMPLETE	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPublicAllowAll	
23:37:20 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPublic	Resource creation Initiated
23:37:20 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPrivate	Resource creation Initiated
23:37:20 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPrivate	Resource creation Initiated
23:37:20 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPublic	Resource creation Initiated
23:37:20 UTC-0400	CREATE_COMPLETE	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPrivateAllowVPC	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPublic	Resource creation Initiated
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPrivate	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPrivate	Resource creation Initiated
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPrivate	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationAPublic	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPublic	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPublic	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetRouteTableAssociation	RouteTableAssociationBPrivate	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationAPublic	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::SubnetNetworkAclAssociation	SubnetNetworkAclAssociationBPrivate	
23:37:19 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Route	RouteTablePublicBInternetRoute	Resource creation Initiated
23:37:18 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Route	RouteTablePublicBInternetRoute	
23:37:17 UTC-0400	CREATE_COMPLETE	AWS::EC2::Subnet	SubnetBPrivate	
23:37:17 UTC-0400	CREATE_COMPLETE	AWS::EC2::Subnet	SubnetAPublic	
23:37:17 UTC-0400	CREATE_COMPLETE	AWS::EC2::Subnet	SubnetBPublic	
23:37:17 UTC-0400	CREATE_COMPLETE	AWS::EC2::Subnet	SubnetAPrivate	
23:37:16 UTC-0400	CREATE_COMPLETE	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	
23:37:05 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPublicAllowAll	Resource creation Initiated
23:37:05 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPrivateAllowVPC	Resource creation Initiated
23:37:05 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPublicAllowAll	Resource creation Initiated
23:37:04 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPublicAllowAll	
23:37:04 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPrivateAllowVPC	Resource creation Initiated
23:37:04 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPrivateAllowVPC	
23:37:04 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryInPublicAllowAll	
23:37:03 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAclEntry	NetworkAclEntryOutPrivateAllowVPC	
23:37:02 UTC-0400	CREATE_COMPLETE	AWS::EC2::NetworkAcl	NetworkAclPublic	
23:37:02 UTC-0400	CREATE_COMPLETE	AWS::EC2::RouteTable	RouteTablePublic	
23:37:01 UTC-0400	CREATE_COMPLETE	AWS::EC2::RouteTable	RouteTablePrivate	
23:37:01 UTC-0400	CREATE_COMPLETE	AWS::EC2::RouteTable	RouteTableBPublic	
23:37:01 UTC-0400	CREATE_COMPLETE	AWS::EC2::RouteTable	RouteTableBPrivate	
23:37:01 UTC-0400	CREATE_COMPLETE	AWS::EC2::NetworkAcl	NetworkAclPrivate	
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetAPrivate	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTablePublic	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTablePrivate	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetBPublic	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAcl	NetworkAclPublic	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetAPublic	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetBPrivate	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAcl	NetworkAclPrivate	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTableBPrivate	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTableBPublic	Resource creation Initiated
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::VPCGatewayAttachment	VPCGatewayAttachment	
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTablePrivate	
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetBPublic	
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTablePublic	
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAcl	NetworkAclPublic	
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetBPrivate	
23:37:00 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetAPrivate	
23:36:59 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTableBPublic	
23:36:59 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::NetworkAcl	NetworkAclPrivate	
23:36:59 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::Subnet	SubnetAPublic	
23:36:59 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::RouteTable	RouteTableBPrivate	
23:36:58 UTC-0400	CREATE_COMPLETE	AWS::EC2::VPC	VPC	
23:36:57 UTC-0400	CREATE_COMPLETE	AWS::EC2::InternetGateway	InternetGateway	
23:36:40 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::VPC	VPC	Resource creation Initiated
23:36:40 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::InternetGateway	InternetGateway	Resource creation Initiated
23:36:40 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::InternetGateway	InternetGateway	
23:36:39 UTC-0400	CREATE_IN_PROGRESS	AWS::EC2::VPC	VPC	
23:36:35 UTC-0400	CREATE_IN_PROGRESS	AWS::CloudFormation::Stack	vpc-2azs	User Initiated

**Comment by michaelwittig** [comment]
you don't set the ParentVPCStack parameter to the name of the vpc stack created earlier?

**Comment by snifsnsort** [comment]
I missed that part. 
Once the parameter was included it all started to work.

Thank you
