### ISSUE TITLE
Whitelist files

### ISSUE THREAD

**Issue by ecoff** [widdix/aws-s3-virusscan#40]
Is there a way to whitelist files to prevent them from being scanned?  I know I can whitelist files in ClamAV.  Is the best way to do this by modifying the template?

**Comment by michaelwittig** [comment]
No, there is no way to whitelist files.

Can you explain what kind of whitelisting you need and how you configure ClamAV?

**Comment by ecoff** [comment]
I have a file in my S3 bucket that lists bad domains and ClamAV is claiming the file is infected and deleting it.  I believe you can add md5s to a .fp file in the ClamAV database directory and it will ignore those files (http://pig.made-it.com/clamav.html).  

What do you think is the best way for ClamAV to "ignore" a file/false positive?

I guess another solution would be to somehow stop the event trigger on particular files - I'm not sure if that's possible with S3.

**Comment by michaelwittig** [comment]
I believe the easiest way is to place such a whitelist file into the appropriate directory.
This would require only a small change somewhere here: https://github.com/widdix/aws-s3-virusscan/blob/master/template.yaml#L594
