### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by arushi-1234** [widdix/aws-s3-virusscan#43]
IS it possible can you provide me the complete workflow of this like how ec2 is scanning what file ec2 will use , how ec2 server doing tagging part etc

**Comment by michaelwittig** [comment]
why don't you start doing the process documentation? You can post it for review here.

**Comment by arushi-1234** [comment]
I need to provide details to my client I mean i follow all steps from your
doc and perfectly fine but we should know whats going on in
background in ec2 server how ec2 server is tagging scanning ..complete
picture .

Really Sorry for asking this .Please help me

**Comment by michaelwittig** [comment]
Are you kidding me? You get money from your client to provide documentation and ask me to do it for you for free?

**Comment by arushi-1234** [comment]
oops sorry if you want me to pay you i am okay with that how much you want
..
