### ISSUE TITLE
EC2 can't consume SQS message.

### ISSUE THREAD

**Issue by TerrificMao** [widdix/aws-s3-virusscan#44]
I launch the template with vpc-2azs.yaml and template.yaml (https://s3-eu-west-1.amazonaws.com/widdix-aws-s3-virusscan/template.yaml).
(1) two templates launched successfully.
(2) EC2, SQS and S3 launched successfully.
(3) already config the s3 event for SQS.
(4) upload the image to s3, I can see the message on s3-virusscan-ScanQueue-EB8H5BNWNH2S, but ClamAV can't consume the sqs message.

I launched these two template 10 days ago, which can work successfully. But the same configuration and I launched again this morning, it can't work. could you pls help check?

**Comment by michaelwittig** [comment]
I released a new version. Can you check if this works for you?
