### ISSUE TITLE
Help me on scripts in ec2

### ISSUE THREAD

**Issue by arushi-1234** [widdix/aws-s3-virusscan#46]
Can you help me out of the scripts which is in EC2 server , I mean from where exactly these scripting are  coming either from user data or manually what is the process behind in background ?

This is required because of server harding

**Comment by michaelwittig** [comment]
We use cfn-init for that. You can configure cfn-init in the `Metadata` section of the launch config : https://github.com/widdix/aws-s3-virusscan/blob/master/template.yaml#L446

Learn more: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html
