### ISSUE TITLE
How long does the virus scan take?

### ISSUE THREAD

**Issue by ivanelrey** [widdix/aws-s3-virusscan#49]
As I understand the new uploaded files are scanned automatically, so the files that haven't completed the scan yet are not available to get them from s3.

Do we know the approximate time that is needed for the virusscan to finish? (I guess it depends on the file size).

I would like to use your solution but was wondering if the files will take too much time until they are available?

**Comment by mouryaamit** [comment]
@ivanelrey yes its depends on file size as well as the queue size. 
I too had the same thinking that how I will know if file scan is completed or not. The approach which I am using is to save file key with status as PENDING and then configuring HTTP(S) POST Method which can hit your server and with that, you can update the file status.

It would the same as [Configure E-Mail subscription](https://github.com/widdix/aws-s3-virusscan#configure-e-mail-subscription) just in place of email you will be subscribing HTTP(S) Method

**Comment by michaelwittig** [comment]
@ivanelrey the files are downloadable as soon as they are uploaded. the scan runs in the background.

**Comment by zmarwa** [comment]
@mouryaamit how can i save file key with status as PENDING please? Which parts of code i need to change? thks
