### ISSUE TITLE
Subscribe the AV SQS queue to an SNS topic?

### ISSUE THREAD

**Issue by lithiumoxide** [widdix/aws-s3-virusscan#51]
Hi,

I have a use case where I need to run multiple things off the same S3 notification. For this I set the notification to go to an SNS topic, and then I subscribe various functions etc to that topic so they can do what they need to do.

When I subscribe the AV SQS queue to the SNS topic, the objects uploaded to S3 don't get scanned. Is it possible to use this AV solution in this manner, and if so, what configuration changes should I make?

Conor

**Comment by andreaswittig** [comment]
Sure, see [Using Amazon SNS for System-to-System Messaging with an Amazon SQS Queue as a Subscriber](https://docs.aws.amazon.com/sns/latest/dg/sns-sqs-as-subscriber.html).

**Comment by lithiumoxide** [comment]
Thanks! On their own, the steps on that page of documentation didn't allow this to work. However, once you enable 'Raw message delivery' on the SNS subscription, the resulting SQS message format seems to allow the EC2 instance to consume the message correctly and run ClamAV against the object. I just wanted to leave this extra note in case others want to implement the same thing.

Thanks again!

Conor
