### ISSUE TITLE
Will it support the "fanout" scenario?

### ISSUE THREAD

**Issue by apedzko** [widdix/aws-s3-virusscan#56]
Hi!

My solution already has a lambda function that is triggered by s3 "object created" event and performs some business logic.

What is the best option to utilize the "aws-s3-virusscan" solution in this scenario since i cannot directly subscribe an SQS queue to the  s3 "object created" event? 

Will i be able to use smth like the "fanout" pattern as described in https://aws.amazon.com/blogs/compute/fanout-s3-event-notifications-to-multiple-endpoints/ and subscribe both my lambda function and the SQS queue for the av scanner to an SNS topic?

**Update 09 September 2019:**
I have conducted an experiment and the "fanout" integration scheme worked just fine.
I believe, my question really comes down to the following:

How do i trigger the scan on-demand?

As far as i can see the s3 object created event message is quite verbose:

```
{
	"Records": [{
		"eventVersion": "2.1",
		"eventSource": "aws:s3",
		"awsRegion": "eu-west-1",
		"eventTime": "2019-09-11T15:31:18.840Z",
		"eventName": "ObjectCreated:Put",
		"userIdentity": {
			"principalId": "{principal id}"
		},
		"requestParameters": {
			"sourceIPAddress": "{source ip}"
		},
		"responseElements": {
			"x-amz-request-id": "{some id}",
			"x-amz-id-2": "{some id}"
		},
		"s3": {
			"s3SchemaVersion": "1.0",
			"configurationId": "{some id}",
			"bucket": {
				"name": "{bucket name}",
				"ownerIdentity": {
					"principalId": "{principal id}"
				},
				"arn": "arn:aws:s3:::{bucket name}"
			},
			"object": {
				"key": "req.txt",
				"size": 4306,
				"eTag": "495255f67ab57a4df5d63744640e93a4",
				"sequencer": "005D791346C7A9728A"
			}
		}
	}]
}

```

Should i send all the s3 object  created event details in a sqs message in case i would like to trigger scanning on demand?

My experiment shows that this is the minimal amount of properties i should send:

```
{
	"Records": [{
		"eventVersion": "2.1",
		"eventSource": "aws:s3",
		"awsRegion": "eu-west-1",
		"eventTime": "2019-09-11T15:31:18.840Z",
		"eventName": "ObjectCreated:Put",		
		"s3": {
			"s3SchemaVersion": "1.0",			
			"bucket": {
				"name": "{bucket name}",				
				"arn": "arn:aws:s3:::{bucket name}"
			},
			"object": {
				"key": "req.txt",
				"size": 4306,
				"eTag": "495255f67ab57a4df5d63744640e93a4"			
			}
		}
	}]
}
```

**Could you please advise:**
1. What is the recommended way of triggering a scan on demand (from code)?
2. Is it ok if i do it by sending a short message provided above?

**Comment by michaelwittig** [comment]
yes. if you follow the S3 Event Schema you are fine
