### ISSUE TITLE
File Size limit

### ISSUE THREAD

**Issue by subhashvz** [widdix/aws-s3-virusscan#57]
Hi,
I am using a "t3 small" Linux instance. when I uploaded a video of 1.47 GB to S3 bucket, I have received the following error in /var/log/messages. Is there a limit on the file size which clamav can scan up to?
If I need to scan files up to 5 GB, should I change my EC2 instance to t3 large or so ?

clamd[2463]: /tmp/586558b2-ee38-4c20-867b-d7556abdc03c: Can't allocate memory ERROR

Thanks,
Subhash.

**Comment by andreaswittig** [comment]
Yes, that should do the trick.

**Comment by subhashvz** [comment]
Thank you so much. I will try to bump up the instance and will see if it helps.

**Comment by subhashvz** [comment]
Hi Team,
Can you please help me out with the logs. 
I am looking for the log where it captures which file is scanned and the status of the file as "infected" or "clean" and any log related to email as well.
Thanks in advance.

**Comment by michaelwittig** [comment]
Hi @subhashvz Have you checked the logs in CloudWatch Logs? https://github.com/widdix/aws-s3-virusscan#troubleshooting
