### ISSUE TITLE
Scanner suddenly doesn't start

### ISSUE THREAD

**Issue by JLPVB** [widdix/aws-s3-virusscan#58]
We have been running the virus scanner for a few months now, but since some time last month it doesn't appear to be scanning files.
I have cleared the scan queue and verified that when new files are uploaded messages are pushed.
I updated our stack with the latest template link and redeployed.

Looking at the logs I found a few lines which lead me to believe something is going wrong, but I can't figure out exactly what it is or how to fix it.

- "cloud-init: Error occurred during build: Could not enable service amazon-ssm-agent (return code 1)"

- "cloud-init[3505]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]"

- "cloud-init[3505]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)"

Any advice you can give me is greatly appreciated.

**Comment by michaelwittig** [comment]
Could you set the `SystemsManagerAccess` parameter to false and try again?

**Comment by ChrisAccsys** [comment]
Appologies if this is a different issue but we too started having some issues last week. During the build of the box our logs are showing:

[DEBUG] Setting service clamd@scan to enabled
[ERROR] chkconfig failed with error 1. Output: error reading information on ervice clamd@scan: No such file or directory
[ERROR] Error encountered during build of config: Could not enable service clamd@scan (return code 1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 270, in build
    CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 155, in apply
    self._set_service_enabled(service, util.interpret_boolean(serviceProperties["enabled"]))
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 234, in _set_service_enabled
    modifier.set_service_enabled(service, enabled);
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/service_tools.py", line 297, in set_service_enabled
    raise ToolError("Could not %s service %s" % ("enable" if enabled else "disable", service), result.returncode)
ToolError: Could not enable service clamd@scan (return code 1)
[ERROR] -----------------------BUILD FAILED!------------------------

As yet we have not had a chance to test setting SystemsManagerAccess to false and trying again but I will try this after the festive period a report back.

Thanks @michaelwittig

**Comment by michaelwittig** [comment]
@ChrisAccsys  do you use the latest version? A fix was released on December 10th https://github.com/widdix/aws-s3-virusscan/commit/485c786ed6066a06fdee2904c54df4a88ffcdc8f

**Comment by ChrisAccsys** [comment]
Ahh I missed that commit! That looks like our issue - thanks @michaelwittig
