### ISSUE TITLE
Email Alerts for Infected Files only

### ISSUE THREAD

**Issue by jkersu** [widdix/aws-s3-virusscan#60]
Hi,

I'm using the S3 VirusScan integration from the AWS Marketplace and have followed the instructions in the README to subscribe to emails to be alerted when a virus was found. It seems to however be sending alerts for both scans of BOTH clean and infected files. Was wondering if there was a way to set it up to only send when the file is infected? Could not seem to find any documentation on this.

**Comment by michaelwittig** [comment]
hi @jkersu 

> AWS Marketplace customers can get support via hello@widdix.net as well.

there are two options to achieve your goal:

1. option: you can disable that clean files are reported:

visit the AWS CloudFormation Console: http://console.aws.amazon.com/cloudformation/
Ensure that you are in the correct region
Click on the S3 VirusScan stack (if you followed our docs the name is s3-virusscan)
At the top right, clock on Update
In the next step, just click Next
Change the `ReportCleanFiles` parameter to `false`
Click Next
In the next step, just click Next
At the bottom, check "I acknowledge that AWS CloudFormation might create IAM resources." and click Update Stack.

2. In your email subscription, add a filter policy to only receive messages where the attribute `status` is set to `no` (scan was skipped) or `infected`.

Michael

**Comment by jkersu** [comment]
Hi,

Thanks, thats reall helpful.
