### ISSUE TITLE
Where are debug logs created by worker.rb

### ISSUE THREAD

**Issue by z-sahil** [widdix/aws-s3-virusscan#61]
I'm trying to test this project on an EC2 instance. I want to see how much time is it taking to scan files of different sizes. In the worker.rb, I see that it is logging start of scanning and end of scanning. But it is sending it to debug log. i am unable to find out the location of the debug.log  
I've found the info log which is located at /var/log/messages

**Comment by michaelwittig** [comment]
The S3 VirusScan sends the debug messages to syslog. BUT syslog does not output debug messages to `/var/log/messages` by default.

To change that (connect to the machine, e.g. via SSM Session Manager) and create a new rsyslog conf file: `/etc/rsyslog.d/3-virusscan.conf` with the following content as root:

```
:programname, isequal, "s3-virusscan"      /var/log/s3-virusscan
```

and restart rsyslog as root:
```
systemctl restart rsyslog
```

Logs will now appear in `/var/log/s3-virusscan`. Keep in mind that the amount of logs could be high. Do not turn this on in production with proper log file roatation.
