### ISSUE TITLE
Cloudformation failing with t2.small

### ISSUE THREAD

**Issue by ChrisAccsys** [widdix/aws-s3-virusscan#62]
Been trying to create new instance of this stack today and it consistanly failed with "unable to allocate memory" when starting the clam daemon on t2.small boxes

Moving to t2.medium solved the issue.

Perhaps the ClamAv db has become even larger now and this no longer works on t2.small either?

**Comment by michaelwittig** [comment]
I added a new parameter `SwapSize` and changed the defaults slightly to provision 2GB of swap
