### ISSUE TITLE
S3 VirusScan AWS Security

### ISSUE THREAD

**Issue by jledae** [widdix/aws-s3-virusscan#63]
Hi, 

I following this article to use ClamAV to scan my S3 bucket for viruses.

https://cloudonaut.io/s3-virusscan-aws-security/

I ran the vpc-*azs.yaml CF template to create the VPC, IGW, subnet.  Then I created my S3 bucket and edit events and I don't see the SQS 'scanner2-ScanQueue' that is referenced in the article to choose from in the drop-box.  I created my own SQS and pointed to that in my s3 buckets events but when I placed the EICAR test virus file I didn't see a SNS email or anything even though I do have a SNS topic tied to the SQS going to my email address.  I tested SNS with a test email and it sent to me successfully.

I think the article above for widdix clamav s3 bucket is missing several steps like sqs, lambda, and clamav creatiosn.  Is there another cloudformation template(s) I need to run to create my widdix ec2 instance(s) with clamav installed, sqs, and lambda?

Thanks,

**Comment by michaelwittig** [comment]
follow this steps https://github.com/widdix/aws-s3-virusscan#installation
