### ISSUE TITLE
VirusScanner not detecting EICAR file png/pdf format

### ISSUE THREAD

**Issue by zmarwa** [widdix/aws-s3-virusscan#64]
Hello, Any idea why EICAR file is scanned as malicious with txt extension but not when changing it in png format!
 Thks

**Comment by michaelwittig** [comment]
Hi @zmarwa 

can you confirm that the file content is still the same after changing the file extension? Sometimes, local antivirus solutions get into your way.

**Comment by zmarwa** [comment]
Exemples of two files I use
https://drive.google.com/drive/folders/1kmZ7LDDDG4_EctUHf3vsPGtVnU-Ms3pW?usp=sharing

**Comment by michaelwittig** [comment]
The folder is empty?

**Comment by zouheirBT** [comment]
Hello Michael, I'm Zouheir, working with Marwa. 
Amazing! The .zip was probably cleaned by Gdrive...
Here is the .png sample
![eicar](https://user-images.githubusercontent.com/63347681/78777966-654db900-7992-11ea-9941-15e377f595bb.png)
Another way to reproduce the issue, is create .png, open it with notepad and feed it with the usual malicious content : X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
Thank you for your help!

**Comment by michaelwittig** [comment]
I created a file with the mentioned content and the file ending png and the file is cleaned as expected. As I mentioned, generating a test file is hard if a you run a local virus scan solution. I recommend to start an EC2 Instance without a virus scan solution to do the testing.
