### ISSUE TITLE
aws-s3-virusscan without public subnet configuration

### ISSUE THREAD

**Issue by ratneswar** [widdix/aws-s3-virusscan#66]
AWS Marketplace customers have access to support via email: hello@widdix.net
Hi Michael,

We are planning to use aws-s3-virusscan in our environment, which does not have access to internet.
does your template works without public subnets configuration?  

Thanks
Ratneswar

**Comment by michaelwittig** [comment]
No, but the commercial offering does. Find it on the AWS Marketplace: https://aws.amazon.com/marketplace/pp/widdix-GmbH-S3-VirusScan/B07XFR781T
