### ISSUE TITLE
ClamAV not working after restarting t2.small EC2 instance

### ISSUE THREAD

**Issue by bungureanu** [widdix/aws-s3-virusscan#70]
Hello,

Could you please assist me on resolving the following issue?

I've installed aws-s3-virusscan using a t2.small EC2 instance almost 1 year ago and everything went fine until a recent reboot. After this reboot the solution stopped working and looking through the logs found the following error:

daemonize() failed: Cannot allocate memory
clamd@scan.service: control process exited, code=exited status=1
Failed to start clamd scanner (scan) daemon.
Unit clamd@scan.service entered failed state.

What is the best way for fixing this issue and prevent it for happening again in the future? It is required to use a different EC2 with more RAM although you guys are recommending to use at least a t2.small?

Thank you.

Have a great day!

Bogdan

**Comment by michaelwittig** [comment]
you need more memory (bigger instance type). The ClamAV virus definitions are growing and growing and they have to fit in memory.

**Comment by bungureanu** [comment]
Thank you for the confirmation. Maybe it would be a good idea to update your documentation with this information as well. :)

Have a great day!

Bogdan

**Comment by michaelwittig** [comment]
@bungureanu feel free to open a PR and do it
