### ISSUE TITLE
SNS topic message to SQS

### ISSUE THREAD

**Issue by anil-venkata** [widdix/aws-s3-virusscan#76]
Hi Team,

This is really a great tool, and it is working as we needed. But the problem here is we are not able to send the message to SQS.

is there anyway we can do that..? 

We have a queues consuming the messages and show the customers as a notification in their portal. So any infected file got detected we would like to send the message to SQS, and from there we will filter based on the client and we will show them as a notification saying "Filename.ext" has some virus and we deleted the file. 

Would be very grateful if it can be done. 

We are in testing phase, if everything works we are planning to buy from the AWS market place. 

Thanks in advance.

**Comment by michaelwittig** [comment]
Hi @anil-venkata 
You can subscribe a SQS queue to the SNS findings topic. Does this satisfy your requirements?
Thanks
Michael

**Comment by anil-venkata** [comment]
@michaelwittig , Thanks for the suggestion, i tried that but that doesn't help. So i added/modified some code in `worker.rb` and it worked .

added `:sqs` to `attr_reader`

and added below line in `def initialize`

`@sqs = Aws::SQS::Client.new()`

and below line above `sns.publish`

`sqs.send_message(queue_url: URL, message_body: message)`

And also gave the SQS permission to IAM role

I am testing this, once i tested i will change the CF template to fit the above changes.

**Comment by andreaswittig** [comment]
@anil-venkata Glad to hear you found a way to implement your requirements.

However, that's not our recommended way of doing so. Therefore, we will neither provide any further support nor merge any PR. As @michaelwittig mentioned, we recommend to add a subscription to the SNS topic to forward messages to SQS. Doing so would not require any code changes at all.

**Comment by anil-venkata** [comment]
@andreaswittig , thanks for the details. But as i mentioned earlier, subscription to SNS topic not helped me. Below are the steps that i followed

1) Create a new queue in AWS SQS
2) Subscribed new SQS queue to the SNS created by CF template
3) Subscribed email to the SNS created by CF template
4) Manually added one file to the bucket

i am getting the mail , but i am not seeing any messages in the Queue. I tried adding the slack alerts too. Neither messages , nor slack alert works , Only mail subscription works.

am i missing something here.?

Upon the confirmation of no messages in queue, i went ahead for the workaround.
