### ISSUE TITLE
Failed to execute command : dpkg-query 

### ISSUE THREAD

**Issue by rmarre** [widdix/aws-s3-virusscan#80]
Hi
We are getting following error while creating ScanAutoScalingGroup, please advice? 

2021-04-07 12:02:35 ERROR [getApplicationData @ dataProvider_unix.go.268] [ssm-document-worker] [6627f34a-4a00-4f11-b2a7-3dff34558939.2021-04-07T12-02-35.290Z] [DataBackend] [pluginName=aws:softwareInventory] [aws:softwareInventory] Failed to execute command : dpkg-query [-W -f={
    “Name”: “<start90beaa28>${Package}<end9befd3e9>“,
    “Publisher”: “<start90beaa28>${Maintainer}<end9befd3e9>“,
    “Version”: “<start90beaa28>${Version}<end9befd3e9>“,
    “ApplicationType”: “<start90beaa28>${Section}<end9befd3e9>“,
    “Architecture”: “<start90beaa28>${Architecture}<end9befd3e9>“,
    “Url”: “<start90beaa28>${Homepage}<end9befd3e9>“,
    “Summary”: “<start90beaa28>${Description}<end9befd3e9>“,
    “PackageId”: “<start90beaa28>${Package}_${Version}_${Architecture}.deb<end9befd3e9>”
},] with error - exec: “dpkg-query”: executable file not found in $PATH

**Comment by michaelwittig** [comment]
Hi @rmarre! Where do you get this error message from? It doesn't look like a CloudFormation errror? Is this from the instance logs? Are you executing SSM documents?

**Comment by rmarre** [comment]
@michaelwittig , stack creation failed with this error, the above error is from error log file (.../var/log/amazon/ssm/errors.log) from the clowdwatch

ScanAutoScalingGroup | 
Test11-ScanAutoScalingGroup-U80S8JZF6K0G | 
AWS::AutoScaling::AutoScalingGroup | CREATE_FAILED | Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
-- | -- | -- | -- | --

**Comment by michaelwittig** [comment]
When you launch the stack, please set the `SystemsManagerAccess` parameter to false and it should work?

**Comment by rmarre** [comment]
@michaelwittig , tried with SystemsManagerAccess as false, still failing...

2021-04-07 11:03:54 UTC-0500 | Test44 | CREATE_FAILED | 
The following resource(s) failed to create: [ScanAutoScalingGroup].
-- | -- | -- | --
2021-04-07 11:03:52 UTC-0500 | ScanAutoScalingGroup | CREATE_FAILED | 
Received 1 FAILURE signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

Parameters are as follows:

AutoScalingMaxSize | 4 | -
AutoScalingMinSize | 1 | -
DeleteInfectedFiles | false | -
IAMUserSSHAccess | true | -
InstanceType | t2.medium | -
KeyName | devops | -
LogsRetentionInDays | 14 | -
ParentSSHBastionStack | - | -
ParentVPCStack | ENVCF | -
ReportCleanFiles | false | -
S3BucketRestriction | * | -
S3ObjectRestriction | * | -
SpotPrice | - | -
SwapSize | 2 | -
SystemsManagerAccess | false | -
TagFiles | true | -
TagKey | clamav-status | -
VolumeSize | 16 | -

**Comment by michaelwittig** [comment]
I'm very confused because of the initial error message. `dpkg` is not used in Amazon Linux 2. Have you modified the template in any way?

What region are you using?

**Comment by rmarre** [comment]
we are in us-east-1, this process has been working successfully last couple of months; suddenly process is returning empty tags. validate the SQS queue and saw some pending queue messages, cleaned / delete those messages, upload some files to s3, still not created tags, when we try to recreate the stack after delete, it failed, no changes in CF Template.

**Comment by rmarre** [comment]
please find cfn-init.log file attached. 
[cfn-init.log.txt](https://github.com/widdix/aws-s3-virusscan/files/6274210/cfn-init.log.txt)

**Comment by rmarre** [comment]
Issue has been resolved after splitting single line commands in separate lines. when I try to debug which command failing, no issues, it went through. not sure why single line leads to fail signal.  

extras2:
          commands:
            a_installs:
              command: 'yum update -y'
            a_progress:
              command: 'echo " a_installs completed " >> /opt/.progress'
            b_installs:
              command: 'yum install -y gem'
            b_progress:
              command: 'echo " b_installs completed " >> /opt/.progress'
            c_installs:
              command: '/bin/gem update -p http://proxyUser:pcode@domain.com:port'
            c_progress:
              command: 'echo " c_installs completed " >> /opt/.progress'
            d_installs:
              command: '/bin/gem install -p http://proxyUser:pcode@domain.com:port daemons:1.3.1 aws-sdk-s3:1.54.0 aws-sdk-sqs:1.23.1 aws-sdk-sns:1.20.0 rubysl-securerandom:2.0.0'
            d_progress:
              command: 'echo " d_installs completed " >> /opt/.progress'

**Comment by michaelwittig** [comment]
modified version
