### ISSUE TITLE
Some questions to confirm.

### ISSUE THREAD

**Issue by daxin09pp** [widdix/aws-s3-virusscan#81]
Hello, 
I am evaluating the S3 anti-virus software. There are 2 questions with Widdix/aws-s3-virusscan that you would like to confirm.
1. Does Widdix/aws-s3-virusScan support regular scanning of all files in my S3?
2. Can Widdix/ aws-s3-virusscan block a virus before it is uploaded to my S3?
Thanks,

**Comment by michaelwittig** [comment]
1. No, but our commercial offering in the AWS Marketplace does. see https://s3-virusscan.widdix.net/
2. No. Files are scanned after they are uploaded. Some customers use two buckets: one for uploading and one where clean files are moved to. See https://s3-virusscan.widdix.net/
