### ISSUE TITLE
EC2 instances should not have a public IP address

### ISSUE THREAD

**Issue by thiwanka-aux** [widdix/aws-s3-virusscan#82]
Recently I have run security assessment of my AWS resources using **AWS Security Hub**. As a result, under the **AWS Foundational Security Best Practices v1.0.0** category, there is a failure that saying 

### **`EC2 instances should not have a public IP address`**

how can we resolve this problem?

**Comment by michaelwittig** [comment]
I recommend to use our commercial product which comes with support for your use case.
1. Go to https://aws.amazon.com/marketplace/pp/B07XFR781T
2. Select the Dedicated private VPC fullfilment option.
