### ISSUE TITLE
Instance Metadata Service Version 2 (IMDSv2)

### ISSUE THREAD

**Issue by thiwanka-aux** [widdix/aws-s3-virusscan#83]
I have enabled Instance Metadata Service Version 2 (IMDSv2) in the ScanLaunchConfiguration CF template. Now template getting failed when its update the stack.

added lines below
```
MetadataOptions:
    HttpEndpoint: enabled
    HttpTokens: required
```

error
![image](https://user-images.githubusercontent.com/47382911/117800319-a63c8f00-b270-11eb-8cb3-e89b3f9c5a84.png)

what is the soution?

**Comment by michaelwittig** [comment]
The software is not compatible with IMDSv2. I recommend to use our commercial offering which comes with IMDSv2 by default: https://s3-virusscan.widdix.net/
