### ISSUE TITLE
Time trace for file scanning for vulnerability

### ISSUE THREAD

**Issue by yashvyas1012** [widdix/aws-s3-virusscan#84]
Hi 

Currently, our application is using an open-source version of Clam AV to scan files for vulnerabilities. The same file when uploaded multiple times, doesn't show standard scanning time and varies every upload time.

Scenario: 
File 1 ->Scan time varies between few seconds to 2 mins. 

Application is hosted on AWS and Clam AV is installed on EC2 machine. 
"32.0 GiB	"
4 vCPUs
r5n.xlarge

Is there any specific configuration or setting that needs to be updated in order to address this issue?

Thanks

**Comment by michaelwittig** [comment]
ClamAV comes with a cache. If it is the same file (hash) it will not scan the file again. You can disable this with the DisableCache setting,
