### ISSUE TITLE
Feature: Create the S3 event notification forwarding in CloudFormation template

### ISSUE THREAD

**Issue by ulziibay** [widdix/aws-s3-virusscan#86]
AWS Marketplace / bucketAV customers have access to support via email: hello@bucketav.com

As is, the CloudFormation template does not have the S3 "Create" Event subscription added to the template. This results in users having to do manual configuration as shown in `Configure your S3 buckets` section of  https://bucketav.com/help/setup-guide/.

It would be great user experience improvement, if you move this manual process to be within the template itself.

**Comment by andreaswittig** [comment]
@ulziibay Yes, that would be great. However, that's not possible. The event notifications are managed by the `AWS::S3::Bucket` resource. However, our stack does not manage the S3 buckets.

Feel free to configure your S3 buckets with CloudFormation and use the `AWS::S3::Bucket` to control the event notifications.
