### ISSUE TITLE
aws-s3-virusscan not processing items from ScanQueue 

### ISSUE THREAD

**Issue by rmarre** [widdix/aws-s3-virusscan#88]
After working successfully for several months, aws-s3-virusscan stopped processing items from the ScanQueue today 9/16/21.
is there any specific services needs to be checked / stop and restart on EC2 (t2.medium)

Thanks in advance.

**Comment by michaelwittig** [comment]
Have you updated to the latest template? AWS releases a breaking changes in the ruby modules...

Besides that, please follow https://github.com/widdix/aws-s3-virusscan#troubleshooting

**Comment by rmarre** [comment]
I tried multiple times with the latest template, failing with the following errors:
The following resource(s) failed to create: [ScanAutoScalingGroup].
Received 0 SUCCESS signal(s) out of 1. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
Failed to receive 1 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.

**Comment by rmarre** [comment]
these are the errors in cfn-init.log

2021-09-22 18:08:49,078 [ERROR] Gem failed. Output: ERROR:  Could not find a valid gem 'daemons' (= 1.3.1), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/specs.4.8.gz)

2021-09-22 18:08:49,079 [ERROR] Error encountered during build of config: Failed to install gem: daemons-1.3.1 (return code 2)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 229, in build
    changes['packages'][manager] = CloudFormationCarpenter._packageTools[manager]().apply(packages, self._auth_config)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/lang_package_tools.py", line 111, in apply
    if self._install_gem(pkg, ver):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/lang_package_tools.py", line 155, in _install_gem
    raise ToolError("Failed to install gem: %s-%s" % (pkg, ver), result.returncode)
ToolError: Failed to install gem: daemons-1.3.1 (return code 2)
2021-09-22 18:08:49,082 [ERROR] -----------------------BUILD FAILED!------------------------
2021-09-22 18:08:49,082 [ERROR] Unhandled exception during build: Failed to install gem: daemons-1.3.1 (return code 2)
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)

**Comment by rmarre** [comment]
Tested commenting these lines, since shows message daemon 1.3.1 already installed. 
#rubygems:
#  daemons: ['1.3.1']
#  'rubysl-securerandom': ['2.0.0']

created stack with the failure option " Reserve Successfully Provisioned Resources " not shows above errors, however, filescan process is not creating any tags. 
Any validation needs to be done for SQS side? 

Thanks in advance.

**Comment by rmarre** [comment]
#rubygems:
#  daemons: ['1.3.1']
#  'rubysl-securerandom': ['2.0.0']

**Comment by rmarre** [comment]
Tested commenting these lines, since shows message daemon 1.3.1 already installed.

#rubygems:
#daemons: ['1.3.1']
#'rubysl-securerandom': ['2.0.0']

created stack with the failure option " Reserve Successfully Provisioned Resources " not shows above errors, however, filescan process is not creating any tags.
Any validation needs to be done for SQS side?

Thanks in advance.

**Comment by rmarre** [comment]
finally all errors are cleared, however SQS Receive message section, message available count increasing, which is SQS queue is not clearing / hanging and tags are not cresting to uploaded file to s3 bucket. 
Any advise? 

Thanks in advance.

**Comment by rmarre** [comment]
finally all errors are cleared, however SQS Receive message section, message available count increasing, which is SQS queue is not clearing / hanging and file scan tags are not creating for uploaded files to s3 bucket.
Any advise?

Thanks in advance.

**Comment by michaelwittig** [comment]
@rmarre The ECONNRESET indicates that don't allow Internet access which indicates that you modified the templates. Is that possible?

**Comment by rmarre** [comment]
@michaelwittig , internet access issue resolved by passing the proxy details, and stack created successfully, however messages are hanging at SQS, when I use latest template file scan process not creating tags, tried several times no success. Process creating tags for old template with the following updates:
1. ruby 2.6 install (command: 'amazon-linux-extras install ruby2.6') under extras2 section in ScanLaunchConfiguration; 
2. under CreationPolicy, timeout value increased from 10 to 30 as follows:
      ResourceSignal:
        Timeout: PT30M
    UpdatePolicy:
      AutoScalingRollingUpdate:
        PauseTime: PT30M

Please advise if I am going wrong direction. 

Pending issue:
When I try to create AutoScalingMinSize with 2, stack is failing, please advise.	

Thanks in advance.

**Comment by michaelwittig** [comment]
Sorry. I'm not going to support custom modifications that are not pushed.

**Comment by rmarre** [comment]
I am more then happy to use your latest template, but not working for me, I try to find the issue and spend lots of time to triage, no luck, hanging the messages in SQS and file tags are not creating, please advise.
