### ISSUE TITLE
New issue with missing XML library

### ISSUE THREAD

**Issue by AndreCouture** [widdix/aws-s3-virusscan#91]
AWS Marketplace / bucketAV customers have access to support via email: hello@bucketav.com

AS of 2021-12-18 we start having issues running the worker.rb. 
We found out that some libraries have changed when now required to install a new xml library (gem install rexm -v 3.2.5)

**Comment by andreaswittig** [comment]
Thanks for pointing that out. Will try to reproduce the issue.

**Comment by andreaswittig** [comment]
The test suite runs without any errors. Could you please provide more detailed information (log messages, used version, ...) about the issue?

**Comment by AndreCouture** [comment]
Thanks
This means it could be from some changes I did or that I’m using the very latest AMI?


As opposed to list all AMI in the mapping, I use this parameter

  LinuxLatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2


This returns the latest current Ami for any region your in.  It gets resolved when you launch the script and any time you do an update.

Maybe you can confirm with the latest AMI.

**Comment by michaelwittig** [comment]
Short summary: You "did changes" and "changed the AMI" and now we should debug your issue? I suggest that you test your custom code yourself?

**Comment by AndreCouture** [comment]
Sorry but I didn’t mean it like that.

It only seems to confirm that the current code needs to be updated if using the newer/more recent AMI.

Regards
