### ISSUE TITLE
Alerts if scanning is not working 

### ISSUE THREAD

**Issue by anil-venkata** [widdix/aws-s3-virusscan#92]
AWS Marketplace / bucketAV customers have access to support via email: hello@bucketav.com

Is there anyway we can add any alerts to slack or email if scan stopped working for any reason. We were faced this issue when there was AWS Ruby SDK changes. Scan was not working and we are not aware it was not working until we check manually.

**Comment by michaelwittig** [comment]
Hi @anil-venkata 
The necessary CloudWatch Alarms are [in place](https://github.com/widdix/aws-s3-virusscan/blob/master/template.yaml#L265-L998).
All you ned to do is to forward them to Slack.
* You can use our own [marbot](https://marbot.io/) to do so. The default config is all you ned.
* AWS Chatbot should also do the trick if configured properly.

**Comment by anil-venkata** [comment]
@michaelwittig , great, that helps, i will take it forward. And appreciate your quick revert.

**Comment by michaelwittig** [comment]
@anil-venkata You are welcome
BTW: I found a blog post with details on how to connect with marbot: https://marbot.io/blog/s3-virus-and-malware-alerting-powered-by-virusscan-for-amazon-s3.html
The steps work for the open source version here as well.
