### ISSUE TITLE
Autoscaling resource creation issue in capetown region. 

### ISSUE THREAD

**Issue by prejithp-repo** [widdix/aws-s3-virusscan#96]
![image](https://user-images.githubusercontent.com/42385714/215086719-28647521-57f5-4564-a8b4-0a345f81cbbf.png)

When I select the Capetown region in AWS, the stack will not create the autoscaling resource. It automatically rollbacks the process of creation. Please help me to resolve this issue. I need to complete the stack creation in capetown region. Image attached for reference.

**Comment by michaelwittig** [comment]
could be related to #95

**Comment by prejithp-repo** [comment]
@michaelwittig could you please commit the changes to the master? I am not expertise in cloudformation templates. Could you please provide me the updated template.yaml file?.

**Comment by michaelwittig** [comment]
@prejithp-repo could you share how you resolved the issue?

**Comment by prejithp-repo** [comment]
@michaelwittig There is no issue with the cloudformation template. Issue resolved by changing the instance type from t2.small to t3.small. In the Capetown region, t2 instance doesn't support.
